### ISSUE TITLE
move by is self and is can't line up docking port (BUG)

### ISSUE THREAD

**Issue by sfsupgrades** [pixelgaming579/Smart-SAS-Mod-SFS#2]
i click navigation, target there is mess up is can't line up to near docking port example capsule and probe
![Screenshot (287)](https://github.com/pixelgaming579/Smart-SAS-Mod-SFS/assets/121486721/b0018b2a-5939-4f8b-88c6-aa2c62d643ff)

**Comment by AstroTheRabbit** [comment]
I cannot tell what is going on in that picture, and Smart SAS does not target specific parts, only the CoM of the other rocket.

**Comment by pixelgaming579** [comment]
won't fix
